### ISSUE TITLE
I'm on Mojave now and it's no longer working with Xbox360 remote or Xbox One remote

### ISSUE THREAD

**Issue by CRide97** [360Controller/360Controller#769] opened 2018-10-09 04:22 UTC
### Type of Controller
Xbox 360 and Xbox One

### OS Version
OS X 10.14 Mojave

### Driver Version
360Controller 0.16.9

### Connection Method
I tried Wired with the Xbox One, Wireless Adapter for the Xbox 360 remote, and Bluetooth for the Xbox One remote. All failed to be recognized.

### Device Name and Info
>Device Name: iMac (Retina 5K, 27-inch, 2017)
<br/>Product ID:
<br/>Vendor ID:

### Response of Controller
Drive does not recognize any controller as connected

### Response in Preference Pane
Does the controller appear in the preference pane? NO. Do all of the buttons, joysticks, and triggers act as expected? N/A because it doesn't appear.

### Detailed Explaination of Issue
I'm guessing the driver needs an update for the new OS, so I'm just hoping to be informed when that update comes and provide any information I can that would be helpful in the new release. I miss having my controllers connect to my Mac. Thanks for all you're doing to make that possible.

**Comment by FranticRain** [comment] 2018-10-10 00:56
Okay, a few things.

1. The driver is confirmed working in Mojave.
2. Bluetooth Xbox controllers are NOT supported by this driver. They will not show up in the preference pane.
3. Wireless Xbox 360 controller are NOT supported as of 10.11. They will not show up in the preference pane.
4. Your device name and info section is wrong, so I'm going to need you to fix that as explained here: https://github.com/360Controller/360Controller#how-do-i-find-my-vendor-id-and-product-id
5. Your controller, when connected with Bluetooth, works without the intervention of the driver. You should be able to play games using that. You can check that it is connected properly with an HTML 5 gamepad tester like this one: http://html5gamepad.com/ If a game doesn't work with the controller in Bluetooth mode, please get in touch with the developer as they should DEFINITELY support the base controller framework built in to macOS.

**Comment by danponce** [comment] 2018-10-12 14:42
Are you gonna give support for wireless Xbox 360 controller someday? (The adapter is not working for me)

**Comment by FranticRain** [comment] 2018-10-12 20:50
@danponce The reason it is no longer implemented is because a change Apple made to the macOS kernel broke the driver. A fix would require a complete rewrite of the driver, which is currently not planned,.

**Comment by salildig** [comment] 2018-10-14 15:51
I am using Mac OS High Sierra Ver 10.13.6 and the Microsoft original USB receiver does not work. I have restarted my Mac and the receiver gets detected but the XBOX 360 controller is unable to connect to it. I checked with an old Microsoft Windows 7 laptop and it works as well as connects well. (Just to eliminate the doubt that the controller and the receiver works)

**Comment by FranticRain** [comment] 2018-10-14 17:11
@salildig Apple doesn't admit that it is ever wrong. They changed their USB code because for some reason, they didn't think it was good anymore. Now it's worse, doesn't work, and they refuse to fix it. It's been broken for 3 macOS versions now and they won't ever fix it. A dedicated programmer could convert the driver to the new protocol, but as Apple doesn't want you writing drivers anymore, there is absolutely 0 documentation for this process. You just have to guess and see if it works now. It's really cool and fun.

**Comment by HappyFanboy** [comment] 2018-10-15 10:34
Maybe I get it wrong, but I have Mojave and an old wireless Xbox360 controller for PC with a usb-dongle. It works just fine. But only with Version .09 with the newest version .10 it does not show the controller?

**Comment by FranticRain** [comment] 2018-10-15 14:00
@HappyFanboy The wireless controllers haven’t been officially supported for a while now. The drivers were still included in the releases so that you could use them at your own risk. Since people apparently refuse to look at the README that says that they aren’t supported, I fully removed them from the driver in 0.16.10. If you want to continue to run them, downgrade to 0.16.9. There isn’t anything you need in the latest release anyway. It’s just a new device release, plus that silent fix to hopefully resolve issues like this one. 

@CRide97 Please make a new issue with the correct information if you still want to pursue this issue. Since this issue has become a dumping ground for unrelated issues, I am going to close it.

**Closed by FranticRain** 2018-10-15 14:00 UTC
Labels: awating response

**Comment by HanSeoulOh** [comment] 2019-04-05 02:15
This is not working on my version of Mac OS X Mojave and I am having the same issues. Namely, that the Xbox360Controller doesn't appear in the preference pane anymore either.

**Comment by FranticRain** [comment] 2019-04-06 03:47
@HanSeoulOh Create a new issue and fill out the template.
