### ISSUE TITLE
Settings Issue with Fortnite

### ISSUE THREAD

**Issue by fastv10** [360Controller/360Controller#778] opened 2018-10-21 04:26 UTC
### Type of Controller
NONE GIVEN

### OS Version
10.13.6

### Driver Version
0.16.10

### Connection Method
NONE GIVEN

### Device Name and Info
(If you don't know this information, please refer to the README for how to find it. Enter N/A if not applicable)
>Device Name:
<br/>Product ID: NONE GIVEN
<br/>Vendor ID: NONE GIVEN

### Response of Controller
NONE GIVEN

### Response in Preference Pane
NONE GIVEN

### Detailed Explaination of Issue
Before each Launch of the Fortnite Game program -  (Mac OS X 10.13.6, 360 driver 0.16.10) I have to select Apple System Preferences-> Xbox 360 Controllers Driver-> Advanced Menu and deselect and reselect the "Pretend to be 360  Controller" check box in order to get the Xbox One Controller to work properly with the game. Please help. Thank You, Ed Sliger

**Comment by FranticRain** [comment] 2018-10-21 05:11
Duplicate of #729, please continue the discussion there.

**Closed by FranticRain** 2018-10-21 05:11 UTC
