### ISSUE TITLE
Latest Driver Release Preventing Display Sleep While Plugged In

### ISSUE THREAD

**Issue by therealbushwhack** [360Controller/360Controller#59] opened 2015-01-20 12:21 UTC
My Gamestop controller is FINALLY supported in this release, but I have another issue. 
As long as the controller is connected via USB, the display fails to go to sleep and I need to remember to unplug the controller so the display sleeps as expected. Is there a way to fix this so the display functions/sleeps as expected? Unplugging the controller when done with it does fix it, but where it is now attached is not the most convenient place to reach to unplug when done...

**Comment by GRPyles** [comment] 2015-07-04 00:59
I came here to confirm that I too am having this issue with it preventing sleep, but unplugging the controller does allow it to sleep. Just throwing this in to see if there is any updates planned.

**Comment by RodrigoCard** [comment] 2015-07-10 04:29
could someone else confirm this?
I will test when I have access to my xbox controllers this weekend.

**Comment by GRPyles** [comment] 2015-08-06 00:30
OK well here's an update not sure if this helps to narrow down the problem, but I felt you should know. I just upgraded to 
Windows 10 on my Boot Camp partition, and was trying the controller out. Once I was done testing I left it plugged in, only to come back an hour later to notice my computer was still awake. I unplugged the controller and it went to sleep after the normal allotment. So basically I'm saying the fault may lie with my controller somehow or the Mac itself. I have a Rock Candy controller if this helps.

**Comment by RodrigoCard** [comment] 2015-08-06 21:13
So you are saying that it is happening on windows too  right?

Em quarta-feira, 5 de agosto de 2015, GRPyles <notifications@github.com>
escreveu:

> OK well here's an update not sure if this helps to narrow down the
> problem, but I felt you should know. I just upgraded to
> Windows 10 on my Boot Camp partition, and was trying the controller out.
> Once I was done testing I left it plugged in, only to come back an hour
> later to notice my computer was still awake. I unplugged the controller and
> it went to sleep after the normal allotment. So basically I'm saying the
> fault may lie with my controller somehow or the Mac itself. I have a Rock
> Candy controller if this helps.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/d235j/360Controller/issues/59#issuecomment-128193205>.
>


-- 
Enviado do Gmail para celular

**Comment by GRPyles** [comment] 2015-08-07 03:36
Yes that is correct. I also re-ran some tests with the controller plugged in on both Mac OS X and Windows. Both times prevented the system from going to sleep, once unplugged they went to sleep as normal. So my question now lies is the Rock Candy controller solely the cause? Well anyway thank you for entertaining my queries on this. I'm puzzled more now than before since I was fine leaving it plugged in on Mavericks and Windows 7 and would sleep just fine. Guess I'll just have to still unplug like I have been.

**Comment by FranticRain** [comment] 2018-06-01 04:46
The question asker found the issue to be not related the driver and I cannot reproduce this issue on a modern version of the driver, so I am going to close it.

**Closed by FranticRain** 2018-06-01 04:46 UTC
Labels: bug, needs confirmation
