### ISSUE TITLE
Xbox 360 controller constantly flashing

### ISSUE THREAD

**Issue by jrilett** [360Controller/360Controller#973] opened 2019-11-16 21:18 UTC
Xbox 360 controller.

Mac OS 10.15.1.

1.00-alpha.5.

Wireless with adapter.

Controller functions fine. Visible in preference pane. 
Official microsoft controller. 

'Enable driver' has been set.

ISSUE:  The ring of LEDs on the controller is constantly flashing. Tested on 4 different controllers different batteries etc. I presume something to do with the low battery indication being faulty.

Many thanks.

**Comment by FranticRain** [comment] 2019-11-17 02:13
Duplicate of #955

**Closed by FranticRain** 2019-11-17 02:13 UTC
