### ISSUE TITLE
With latest update controller keeps connecting/will vibrate, then turn off, and then connect again.

### ISSUE THREAD

**Issue by rowanfeely** [360Controller/360Controller#306] opened 2016-07-07 05:05 UTC
el capitan 10.11.5 and 0.16.1

**Comment by FranticRain** [comment] 2016-07-07 05:39
What controller are you using? Can you recreate this issue with 0.16 or is it exclusive to 0.16.1?

I have tested using a Microsoft Xbox One controller in both 2013 and 2015 variants, in addition to a wireless Xbox 360 controller on 10.11.5 and I cannot recreate this issue.

**Comment by dtascarella** [comment] 2016-07-07 13:12
I am having the same issue. Running OS X 10.11.5 using the latest x360 driver you released.


If you want I can record a video, but here is the issue:
After reboot, you plug in the controller via USB into the mac. The mac recognizes it and the controller vibrates, right after the vibrates the controller loses contact with the mac and the mac reattempts to connect to the controller. Its stuck in this cycle.

**Comment by FranticRain** [comment] 2016-07-07 13:30
Once again, what controller are you using? Can you recreate with 0.16? There have been almost no changes in the driver implementation between 0.16 and 0.16.1 looking at the commit history. My best guess is that you are using Xbox One controllers, likely third party, that don't like the altered init packets, but I actually need to know what controllers you are using instead of just saying "it doesn't work and here's how it doesn't work."

**Comment by dtascarella** [comment] 2016-07-07 13:38
Where can I get 0.16? I'm using the official Xbox One Controller that came with my Xbox One when I bought it last year, nothing third party or anything.

**Comment by FranticRain** [comment] 2016-07-07 13:40
The releases page contains every single release of the driver. https://github.com/360Controller/360Controller/releases

I'd also really like to know how you downloaded the driver without viewing the releases page like that.

**Comment by trukhinyuri** [comment] 2016-07-07 14:02
Bug reproduced only in 0.16.1, 0.16 works correctly. XBOX One original controller.

**Comment by dtascarella** [comment] 2016-07-07 14:05
Yup I got it to work in 0.16 it doesn't disconnect or anything, works perfectly fine. Plug it back into 0.16.1 it starts the whole cycle again.

**Comment by FranticRain** [comment] 2016-07-07 14:10
Okay. I've got a new set of init packets that I've been working on that seem like they might cover all three Xbox One controller firmware areas (old firmware, new firmware, third party). This being the group that has old firmware, #257 being new firmware, and #300 being third party. So I'm going to need all three groups to test these new init packets and fingers crossed, it will work for everyone.

Download and install this version of the driver: https://drive.google.com/file/d/0B5PLCKoMd4zGSnNRVUV5V3AwTVk/view?usp=sharing

**Comment by rowanfeely** [comment] 2016-07-07 21:51
I have a legit microsoft xbox one controller and all versions of the driver worked perfectly up until the update, brought it back to 0.16 and worked fine again until reinstalled the latest release.

**Comment by FranticRain** [comment] 2016-07-07 21:53
@rowanfeely Please try the version listed in the comment directly above yours. It should solve your problem. If I can get confirmation that it works with other problematic controllers then I will push it out to a 0.16.2.

**Comment by steven807** [comment] 2016-07-08 23:40
I had the same problem, and tried the version mentioned in the comment above, which fixed things nicely.  Thanks!

**Comment by RodrigoCard** [comment] 2016-07-09 03:29
I just experienced the same issue in 0.16.1
BUT, I noticed that, if you press the guide button once, as you normally do to connect it wirelessly, it works. It also works if the controller is blinking.

**Comment by RodrigoCard** [comment] 2016-07-09 03:39
Please check my answer in #257

**Comment by FranticRain** [comment] 2016-07-09 15:07
I'm going to go ahead and push out a 0.16.2 that should work for everyone, because getting fresh faces in to complain about issues is a whole lot easier than getting previous issue holders in actually respond to questions.

Something something better to ask for forgiveness than to ask permission.

**Comment by FranticRain** [comment] 2016-07-09 15:14
Marking this as resolved with the release of 0.16.2.

**Closed by FranticRain** 2016-07-09 15:14 UTC
