### ISSUE TITLE
Allow axis inputs to be reconfigured to function as buttons

### ISSUE THREAD

**Issue by AmoebaMan** [360Controller/360Controller#182] opened 2015-12-17 21:42 UTC
This came up when using the Xbox One controller. The two triggers are technically axis inputs, like the thumbsticks. Correspondingly, they can't be mapped to button functions. It'd be really awesome if axis inputs could be configured to function like buttons (maybe even with a configurable activation threshold).

**Comment by FranticRain** [comment] 2016-02-11 05:26
From #155 which this is a duplicate of.
"Remapping triggers as buttons is not a great idea. You would have to go through a series of buttons to get to the one you wanted, and then precariously hold a trigger in just the right position for the perfect amount of time. Additionally, it creates so much space for user error. Like imagine a trigger with one of the buttons mapped to start. Then you would open the menu for the game every time you tried to get to a specific button. The entire remapping menu would be a complete mess."

**Closed by FranticRain** 2016-02-11 05:26 UTC
