### ISSUE TITLE
xbox elite controller won't connect to my MacBook Pro (wired)

### ISSUE THREAD

**Issue by Zipcode16** [360Controller/360Controller#1006] opened 2020-01-17 11:52 UTC
xbox elite white

os 1.15.2

version 1.0.0 alpha5

wired

N/A

buzzes then slowly flashes but doesn't connect and turns off after a while

does not appear

the controller will not connect or appear for the driver at all and says no devices found

**Comment by FranticRain** [comment] 2020-01-17 13:30
Duplicate of #966

**Closed by FranticRain** 2020-01-17 13:30 UTC
