### ISSUE TITLE
Xbox 360 controller wireless for Mojave 10.14.4

### ISSUE THREAD

**Issue by jockrlos36** [360Controller/360Controller#864] opened 2019-04-22 00:31 UTC
Hi, i’m new
I Want to know if there is or will exist driver for wireless control of Xbox 360 in the Mojave, since none of the current works. Any News? Best regards

**Comment by FranticRain** [comment] 2019-04-22 01:17
Duplicate of #809

**Closed by FranticRain** 2019-04-22 01:17 UTC
