### ISSUE TITLE
(beta 4) Pretend 360 messes button mapping

### ISSUE THREAD

**Issue by RodrigoCard** [360Controller/360Controller#198] opened 2016-01-14 22:32 UTC
I just quickly tested and noticed that the default button mappings for xone controllers are wrong when the new "pretend 360" box is checked.
* Reattaching the controller doesnt fix the problem
* reset remapping wont work too.

**Comment by FranticRain** [comment] 2016-01-14 22:48
I tested this before I released it. Weird that it worked for me, but somehow broke for you. I'll check it out in a bit.

**Comment by FranticRain** [comment] 2016-01-14 23:22
It looks good to me. What are you testing with that sees a problem?

**Comment by RodrigoCard** [comment] 2016-01-14 23:34
just a single regular 2013 xbox one controller, no other USB devices connected except for a Microsoft mouse, if that matters.

I will do a clean install and try again, just to be sure.

**Comment by FranticRain** [comment] 2016-01-15 02:01
I tested with a 2013 controller and it looks perfectly fine to me.

**Comment by RodrigoCard** [comment] 2016-01-16 16:58
So, I uninstalled the driver, installed it cleanly. My results are now, somehow.... worse!
please check the pictures:

1 - First time I connected the controller after a a fresh install/fresh boot, wrong mappings:
![2016-01-16 14 40 42](https://cloud.githubusercontent.com/assets/417968/12373421/20cd4744-bc60-11e5-94e0-7a418b913519.jpg)

2 - After clicking "start remapping" and "reset remapping" once, now the mappings are correct:
![2016-01-16 14 42 53](https://cloud.githubusercontent.com/assets/417968/12373437/684e4316-bc60-11e5-9529-724cd6b7a0d6.jpg)

3 - "Pretend 360" checked, incorrect mappings (and different from 1 and 2), "reset remapping" trick doesnt make difference.
![2016-01-16 14 42 00](https://cloud.githubusercontent.com/assets/417968/12373448/aa1b726e-bc60-11e5-9b44-12bf3eb682ba.jpg)

** Note that, in all pictures, I am holding only the ABXY buttons, at the same time. they should be 0123 indexes (not respectively) to match the expected behaviour since the first version of the driver **

The app I used for checking the button indexes is my own "Joystick Show", I sell it for a buck, but, whatever, get it for free here: https://dl.dropboxusercontent.com/u/14890209/Joystick%20Show.app.1.1.2.beta.zip

By the way, I am on Yosemite 10.10.5

**Comment by FranticRain** [comment] 2016-01-16 17:18
I'm on 10.11.2, and I can't recreate any of these problems with a 2013 controller. I have no idea what the issue is.

**Comment by RodrigoCard** [comment] 2016-01-16 17:27
So, in all cases, running 10.11.2 you get the correct mappings?

I will install 10.11.2 in another partition if that is the case, cant update my main environment yet.

**Comment by d235j** [comment] 2016-01-16 17:29
@RodrigoCard what version of Mac OS X are you running? I'd prefer that we don't force users to upgrade to the latest major release.

**Comment by RodrigoCard** [comment] 2016-01-16 17:30
@d235j 10.10.5  , latest yosemite. Yeah, I dont like upgrading too fast, stuff breaks.

**Comment by FranticRain** [comment] 2016-01-16 17:31
Correct. When I plug it in, it works by default. When I change to pretend 360 and then disconnect and reconnect the controller, it works just fine. I have no idea why the OS version would change anything. All of this stuff is super basic.

**Comment by RodrigoCard** [comment] 2016-01-16 17:33
@FranticRain right! I will try 10.11.2 in my mac.

Could anyone in 10.10.5 and a xbox one controller test that? 
@d235j @MaddTheSane @electric-monk

**Comment by TyanColte** [comment] 2016-01-16 22:16
@FranticRain I'm running latest El Cap and i'm getting the same issues @RodrigoCard is getting the same stuff i posted in the issue i created last night.

**Comment by FranticRain** [comment] 2016-01-18 01:42
@RodrigoCard Let me know if this fixes your problems. It does nothing for Elite controllers. https://drive.google.com/file/d/0B5PLCKoMd4zGNy15NFR1TTRxVkE/view?usp=sharing

**Comment by larianstudios** [comment] 2016-01-18 14:24
Same here 10.10.5 pretend button messes up things.

**Comment by larianstudios** [comment] 2016-01-18 14:33
@FranticRain Tested from drive:
Button messed up fixed for 'Pretend'
Bug: Pretend button state is not saved between disconnection
Bug: Clicking 'Pretend' does not switch modes more than once
And even more issues with 'Pretend'

**Comment by RodrigoCard** [comment] 2016-01-18 17:59
Installed 10.11 in another HDD and here are my results:

**Current Beta4 in El Capitan:**
- The same as @FranticRain , did not experience the same issues I reported, except for the first connection. chaging any settings avoids the issue.

**The new version from google drive ( tested in both El Capitan and Yosemite ):**
- *No mapping issues anymore, even in the first connection! Nice!* :D 
- Looks like "pretend" works only in once per connection, to disable you need to re-insert the controller. no big deal for now. 
- It is usable in Towerfall again in "Pretend" mode! :)

**Comment by FranticRain** [comment] 2016-01-18 18:05
Awesome. I'll keep working on it, and that should fix it. Basically, the driver now always re-organizes Xbox One packets to match 360 controller packets. Everything uses the 360 HID, and pretty much the only difference between the two is the PID.

**Comment by FranticRain** [comment] 2016-01-19 06:11
@RodrigoCard Any idea how we can do a better job of changing between Pretend360 and Normal? That PadDisconnect(), PadConnect() process is full of issues, as you can see with Joystick Show. I'm thinking, maybe disabling and then enabling the controller after Pretend360 is activated. Any ideas?

**Comment by RodrigoCard** [comment] 2016-01-19 20:51
well, I am not too much aware of some of the internals, maybe worth a shot...
But disabling and re-enabling the controller using the "enable driver" check box OR physically, seems to revert back to "non-pretend" state even if it is enabled.

**Comment by FranticRain** [comment] 2016-01-25 16:51
Resolved in Beta 5.

**Closed by FranticRain** 2016-01-25 16:51 UTC
