### ISSUE TITLE
doesn’t work on an Intel-based Mac

### ISSUE THREAD

**Issue by kelseyojo** [360Controller/360Controller#877] opened 2019-05-07 17:31 UTC
### OS Version
10.13.6

### Driver Version
alpha 2

### Response in Preference Pane
controller does not show up 

### Detailed Explanation of Issue
The driver appears in my system preferences, but won't open and gives the error "You can’t open Xbox 360 Controllers preferences pane because it doesn’t work on an Intel-based Mac." Because of this I am also unable to access the uninstall option. This was after I had to re-download my OS because my mac would get stuck on login. How do I resolve this issue and uninstall the driver?

**Comment by FranticRain** [comment] 2019-05-07 19:39
Duplicate of #876 

There is a zip in that issue that will solve your problem.

**Closed** 2019-05-07 19:39 UTC
Labels: duplicate, rewrite bug
