### ISSUE TITLE
XBox One Elite Controller - No Device Found

### ISSUE THREAD

**Issue by p16774** [360Controller/360Controller#197] opened 2016-01-11 00:09 UTC
The new Beta 3 does not recognize the XBox One Elite Controller. If there is anything I can do to help test drivers, I'm happy to help. Original XBox One Controllers work very well.

**Comment by FranticRain** [comment] 2016-01-11 00:11
Duplicate of #160.

Please pay more attention before making a new issue.

**Closed by FranticRain** 2016-01-11 00:11 UTC
