### ISSUE TITLE
Xbox One Controller Not Found

### ISSUE THREAD

**Issue by Chris-Anime** [360Controller/360Controller#961] opened 2019-11-04 01:59 UTC
### Type of Controller
Xbox One

### OS Version
macOS Mojave
10.14.6

### Driver Version
1.0.0-Alpha-4

### Connection Method
Wired

### Device Name and Info
>Device Name: N/A
<br/>Product ID: 0x02ea
<br/>Vendor ID: 0x045e

### Response of Controller
Controller Vibrates, but does not light up.

### Response in Preference Pane
Does not act at all

### Detailed Explaination of Issue
I've tried connecting using different USB cables to see if it's the charging cable vs data cable, and i'm certain i'm using a data cable. I think I allowed the driver in preferences, but i'm not 100 percent sure. I'm not sure how to solve the issue, and I've been looking through other posts, but not many line up with my macOS.

**Comment by FranticRain** [comment] 2019-11-04 03:23
Can you go into the advanced settings of the driver and check the "enable driver" checkbox? It will provide you will some debug information that should help you resolve your issues. Let me know if you get any errors from it.

**Comment by Chris-Anime** [comment] 2019-11-04 03:26
Ok, so I tried to click enable driver and got this message,
"The driver has failed to load due to an unknown error, code: -603946986. Please report this error to the driver maintainer."

**Comment by FranticRain** [comment] 2019-11-04 03:29
This is a known issue and will be fixed in the next version. For now, alpha 3 should work for you.

**Comment by Chris-Anime** [comment] 2019-11-04 03:30
Ok, thanks for the help

**Comment by FranticRain** [comment] 2019-11-04 04:39
This should be resolved in alpha 5. Let me know if it works for you.

**Comment by Tzhies** [comment] 2019-11-04 17:15
Hi FranticRain,
I just downloaded the alpha 5 and still got the described problem with the driver saying "Cannot load driver" and the following error message.

**Comment by tarokker** [comment] 2019-11-06 10:39
Hi, I don't know if it's ok for me to join the topic or if you prefer to open a new issue:

it seems like I have the same problem with my Xbox one Controller: I attach the cable, the controller bibrates, but does not light up.

I started on Mojave with alpha4 and the infamous error ""The driver has failed to load due to an unknown error, code: -60394698".

Then I uninstalled the driver, installed alpha5 and the error went away, but the controller still didn't light up.

This morning I uninstalled the driver, installed Catalina e reinstalled the alpha5 driver, but still it doesn't light up :(

Please let me know if I could help you with some debug or logs..

Thanks in advance

**Comment by FranticRain** [comment] 2019-11-06 13:10
@tarokker I'd appreciate it if you could make a new issue just so I can get all of the template data from you. It helps a lot in solving these sorts of issues. Also, if you could, go to the "advanced" tab of the preference pane and check the "enable driver" button. I'm sure you know that it'll give you some debug output to try if something is wrong. I'd love to know if it's giving you any errors or not.

**Comment by Joshuasony** [comment] 2019-12-25 00:20
I'll join this discussion since I had the same issue but now it works with Alpha 3. 
First I installed the newest version Alpha 5. Wouldn't work. Then Alpha 4, also wouldn't work. 
First my issue was that the controllers light would only light quickly after plugin in the controller. Then the light would disappear and the controller wasn't listed in the settings. With Alpha 4 it was constantly lighting up (Player 1), but still not listed. With Alpha 3 Player 1 is constantly lighting up and the controller was detected. 
I'm using a wired glow controller.

**Comment by FranticRain** [comment] 2019-12-25 01:23
@Joshuasony Mind giving this build a shot? 

[360ControllerInstall.dmg.zip](https://github.com/360Controller/360Controller/files/3993107/360ControllerInstall.dmg.zip)

**Comment by Joshuasony** [comment] 2019-12-25 22:55
Hi @FranticRain, this seems to work as well. Did you find the cause of the issue?

**Comment by FranticRain** [comment] 2019-12-25 23:51
@Joshuasony Yup. It was the way I was building the driver. Catalina messed up my whole build system so I had some bad builds that I put up.

Going to go ahead and close this one, since the fixed build is out there now.

**Closed by FranticRain** 2019-12-25 23:51 UTC
Labels: awaiting response, duplicate, rewrite bug
