### ISSUE TITLE
Rumble power draw

### ISSUE THREAD

**Issue by CurlyBen** [360Controller/360Controller#501] opened 2017-07-20 02:16 UTC
Hi, I just tried the driver (0.16.5) with a genuine Xbox 360 wired controller and a 13" MacBook Pro Retina (early 2015 - A1502, MacOS Sierra 10.12.5). The installation went smoothly and the controller was recognised immediately when I plugged it in. 

I tested the buttons and everything worked fine, and I pulled both triggers which triggered both rumble motors. However, after a couple of seconds I got a notification from OSX telling me USB devices had been disabled due to excessive current draw. Since then, whenever I plug the controller in either nothing happens (and it's not recognised by the driver) or I get the excessive current draw notification again. It seems my MacBook can't provide sufficient power for both rumble motors at full power simultaneously. Interestingly, according to the sticker on the back, it should only draw 400mA, which should be well within the MBP's ability to deliver.

I've tried restarting the machine and resetting the SMC and PVRAM (which seem to be the standard responses to this error, according to Google), but the controller has not been recognised since that event.

The USB ports still seem to work fine with thumb drives/iPhone/external hard drives, so it doesn't seem that there's been any major damage. My guess is OSX has blacklisted the controller as a device that draws too much current and so it simply refuses to provide any power when it's connected. It doesn't appear in the USB device tree when looking at the System Report.

It's maybe worth tweaking the driver so that it either only activates one rumble motor at a time or limits the intensity when both are activated. Alternatively, the duration that both motors are allowed to run at full power could be limited.

**Comment by FranticRain** [comment] 2018-06-01 04:50
I tested an Xbox One controller for a full minute spinning the trigger motors and the bigger rumble motors at maximum force. I was unable to reproduce this issue. I believe it may be an issue with your individual setup and not related to the driver. We prefer to keep the driver as a driver and are remiss to add individualistic fixes to it for scattered issues. That is the responsibility of user space applications. As such, I am going to close this issue.

**Closed by FranticRain** 2018-06-01 04:50 UTC
Labels: bug
