### ISSUE TITLE
Player 1 led is not lit up

### ISSUE THREAD

**Issue by R-033** [360Controller/360Controller#962] opened 2019-11-04 07:25 UTC
### Type of Controller
Xbox 360

### OS Version
Catalina

### Driver Version
1.0.0-alpha.4

### Connection Method
Wired

### Device Name and Info
>Device Name: Inno GamePad..
<br/>Product ID: 0x028e
<br/>Vendor ID: x045e

### Response of Controller
When connected, 1 and 4 are being lit, then all of them for split second, and then none of them are lit up ever

### Response in Preference Pane
Everything works as expected, except controller being recognised as white instead of black

### Detailed Explaination of Issue
When Xbox 360 controller is connected to pc green led for player 1 should be lit up, but it isn't.
I remember it being lit up before I installed this driver. Is there a way to lit it up or control lights in any way?

**Comment by FranticRain** [comment] 2019-11-04 13:40
This looks like a duplicate of #946, and we don't support Inno GamePads because they are counterfeit Xbox controllers. Closing this. Follow that issue for updates on a solution.

**Closed by FranticRain** 2019-11-04 13:40 UTC
