### ISSUE TITLE
Wried 360 Controller not working

### ISSUE THREAD

**Issue by PWAG** [360Controller/360Controller#823] opened 2019-01-07 23:28 UTC
### Type of Controller
 Xbox 360

### OS Version
macOS Mojave 10.14 (18A391)

### Driver Version
0.16.10 and 0.16.8

### Connection Method
Wired

### Device Name and Info
Product ID:	0x028e
  Vendor ID:	0x045e  (Microsoft Corporation)
  Version:	1.14
  Serial Number:	2567D72
  Speed:	Up to 12 Mb/sec
  Manufacturer:	©Microsoft Corporation
  Location ID:	0x14320000 / 5
  Current Available (mA):	500
  Extra Operating Current (mA):	0

### Response of Controller
im using a newer mac book, so i have my wired controller plugged into a usb hub, when plugged in the rings light up for a few seconds then die

### Response in Preference Pane
nothing appears in the preference pane

### Detailed Explaination of Issue
ive tried doing most of the tricks ive seen online getting this to work, installing 0.16.8 etc. ive uninstalled and reinstalled many times, checked the system privileges many times as well, once i plug in my 360 controller the rings light up then die after a few seconds

**Comment by FranticRain** [comment] 2019-01-08 00:38
You must update your original post with your controller information. A guide on how to do so can be found here: https://github.com/360Controller/360Controller#how-do-i-find-my-vendor-id-and-product-id.

Controller information is only not required for issue that do not involve controllers. For example, a feature request that isn't specific to any controller, or maybe a typo somewhere in the code or documentation. For all issues individuals have with getting a controller working, controller information is ABSOLUTELY VITAL to solving your problem. Not only does it let us know if your controller is already supported, it also lets us know that the operating system can see the controller and is a crucial step in resolving your issue.

Please also run this command in your terminal and tell me what the output is:
```
sudo kextutil /Library/Extensions/360Controller.kext
```

Please notify my when you have updated your original post with your controller information, or let me know if you are unable to find it.

**Comment by PWAG** [comment] 2019-01-08 02:45
Hello, i have updated my original post with the proper info for the controller, this is what came up when i ran the command 

Alexs-MacBook-Pro:~ alex$ sudo kextutil /Library/Extensions/360Controller.kext
Password:
Notice: /Library/Extensions/360Controller.kext has debug properties set.
Kext rejected due to insecure location: <OSKext 0x7f8e64626050 [0x7fff942da8e0]> { URL = "file:///Library/StagedExtensions/Library/Extensions/360Controller.kext/", ID = "com.mice.driver.Xbox360Controller" }
Kext rejected due to insecure location: <OSKext 0x7f8e64626050 [0x7fff942da8e0]> { URL = "file:///Library/StagedExtensions/Library/Extensions/360Controller.kext/", ID = "com.mice.driver.Xbox360Controller" }
Diagnostics for /Library/Extensions/360Controller.kext:
Warnings: 
    Personality CFBundleIdentifier differs from containing kext's (not necessarily a mistake, but rarely done): 
        ChatPadKeyboardEvents

Alexs-MacBook-Pro:~ alex$

**Comment by FranticRain** [comment] 2019-01-08 04:16
So the result of your `kextutil` is telling me that you haven't approved the kext properly yet. Since you aid that you've looked into the approval before, my guess is that you have some sort of other interface device connected to your computer, like a Wacom tablet, or even a flight stick, or maybe even some weird mice. These devices actually make macOS think that a program is trying to click the button, instead of an actual user. This means that the operating system accepts your input, but it doesn't actually execute the approval. Make sure to unplug any devices that may be interfering with the approval, and then follow the following instructions:

Please ensure that the driver has been allowed in System Preferences -> Security and Privacy -> General. This approval UI is only present in the Security & Privacy preferences pane for 30 minutes after the alert. The alert can be triggered again by connecting your controller to the machine. Until you approve the kext, future load attempts will cause the approval UI to reappear but will not trigger another user alert.

![Security and Privacy panel in the macOS System Preferences](https://user-images.githubusercontent.com/33877645/33092253-965b666e-cec7-11e7-940d-3e13b46ca500.png)

**Comment by PWAG** [comment] 2019-01-08 04:30
HI,
the only thing i have plugged is a USB Dock that i need, since i have a newer mac which only has USB C ports, so i need the dock to plug in my controller, trying to reinstall now with the Dock unplugged. i installed like it normally would but did not ask for any approval and my system preferences look like this.
<img width="667" alt="screen shot 2019-01-07 at 11 24 45 pm" src="https://user-images.githubusercontent.com/46464156/50809717-8b8a3200-12d3-11e9-9cb7-0fdeca4e4bf4.png">

**Comment by FranticRain** [comment] 2019-01-08 13:00
I can't say for sure, but given the information that I have, it seems like the USB-C dock is the problem. USB-C is a difficult standard to implement and macOS is beyond finicky about what it accepts when it comes to Gatekeeper prompts, because it's a potential attack vector on their users. I don't know of any sort of "confirmed working" USB-C adapters either. People complain when it doesn't work, but no one really informs me when everything works fine with their system.

Maybe someone else can jump in here and provide some assistance, but the way it stands now, it's an issue with your ability to get the operating system to load the driver. I'm going to go ahead and leave this open so that maybe someone can come along and help you, but there's nothing more I can do.

**Comment by PWAG** [comment] 2019-01-08 15:01
ok thank you  for your help, i have extra xbox one controllers, i will see if i cant get one of those to work ..

**Comment by rileydr** [comment] 2019-01-14 07:15
I'm having a similar issue with my wired 360 controller. 

______________

**Computer**
iMac (Retina 5K, 27-inch, Late 2015)

**OS Version**
macOS High Sierra - 10.13.4
______________

**Type of Controller**
Xbox 360

**Connection Method**
Wired

**Device Name and Info**
Product ID:	0x028e
  Vendor ID:	0x045e  (Microsoft Corporation)
  Version:	1.10
  Serial Number:	194831E
  Speed:	Up to 12 Mb/sec
  Manufacturer:	©Microsoft Corporation
  Location ID:	0x14200000 / 9
  Current Available (mA):	500
  Extra Operating Current (mA):	0

______________

**Driver Version**
Version 0.16.10

**Response of Controller**
Same as OP - "When plugged in the rings light up for a few seconds then die"

**Response in Preference Pane**
"No devices found" shows in the dropdown on the Controller Test page.
The Enable Driver option in the Advanced page will show as unchecked if I navigate away. I can check it after inputing my password, but it will come unchecked again after navigating away and returning.

In Security & Privacy preferences, I see the message: 

> System software from developer "Drew Mills" was blocked from loading.

But selecting the "Allow" button seems to do nothing.

**Comment by FranticRain** [comment] 2019-01-14 13:16
@rileydr What other devices are connected to your computer? Do you have a Wacom tablet or something like that connected?

**Comment by rileydr** [comment] 2019-01-14 16:55
@FranticRain - I have software installed for a few different input devices, including a wacom tablet, but none of them are plugged in.

**Comment by FranticRain** [comment] 2019-01-14 17:24
@rileydr Are you using any sort of software that modifies your inputs, such as Karabiner?

**Comment by rileydr** [comment] 2019-01-14 18:58
@FranticRain - No

**Comment by FranticRain** [comment] 2019-01-14 19:18
I don't know what software or hardware you two have in common, but this is a macOS issue. It's their crazy security on that button that causes this problem. It could literally be anything blocking you at this point, but you haven't even gotten to the driver at this point. You're still fighting macOS, and I don't know how to fix that.

**Comment by rileydr** [comment] 2019-01-14 20:15
That's totally fair. Thanks for looking into it for us!

**Comment by PWAG** [comment] 2019-01-14 21:14
its frustrating because im having issues with other hardware as-well. i had all these things working on my old mac, that suddenly just dont work on my new one

**Comment by FranticRain** [comment] 2019-01-15 01:11
@HaHeho Xbox 360 Controllers aren't supported via wireless receivers. If you have further questions, make a new issue. Your issue is unrelated to this problem.

From the README here: https://github.com/360Controller/360Controller#wireless-xbox-360-controllers
>As of macOS 10.11, Wireless Xbox 360 controller support causes kernel panics. This issue cannot be resolved with minor changes to the driver, and requires that the driver be re-written from scratch to resolve the issue. Due to an excess of caution, we have disabled Wireless Xbox 360 controller support as of 0.16.6. If you want to use a wireless controller, download 0.16.5 or earlier and disable the driver before the computer enters a "sleep" state in order to prevent kernel panics. Alternatively, you can revert to a macOS version before 10.11 to avoid this issue.


@PWAG Your issue isn't really related to the one discussed earlier today, but people love to dog-pile on the top related issue if the name is generic enough and hoo-boy you picked a generic one, so this one is going to be fun for your notifications. Your issue is somehow with macOS not prompting you with the confirmation, and we know that you haven't accepted it, as opposed to being able to see it and not actually accept it. The debugging process for you is completely different from all of the other stuff I talked about today. My best guess for you is one of two things. Potentially, you have a knockoff Xbox 360 controller and the OS is just ignoring it because it's a fake controller. Alternatively, I just want to make sure that you are using a wired controller, and not a "Play and Charge Kit" attached to a Wireless Xbox 360 controller. I forget what the VID and PID combinations are for that, but I don't think you're actually doing that. I just want to make sure.

**Comment by PWAG** [comment] 2019-01-15 01:21
@FranticRain the controller i have is an official Xbox 360 controller, and it is a wired controller no plug and play. I have not gotten an "allow" button but i have had a button that says "open anyway", when installing the driver. i have also purchased a dongle from the apple store from USB C male to USB A Female, and that didnt solve the problem either.

**Comment by PWAG** [comment] 2019-01-15 01:40
@rileydr i saw this on a forum does this help with the grey'd out allow

<img width="1011" alt="screen shot 2019-01-14 at 8 39 35 pm" src="https://user-images.githubusercontent.com/46464156/51153042-9e08ec00-183c-11e9-937f-0f903d195529.png">

**Comment by rileydr** [comment] 2019-01-15 05:06
@PWAG @FranticRain - I changed that keyboard setting and it doesn't seem to have helped anything. To clarify - the allow button is not greyed out. It's clickable, but clicking it doesn't do anything other than change the color of the button for the duration of the click - lol. 
<img width="662" alt="screen shot 2019-01-14 at 9 02 37 pm" src="https://user-images.githubusercontent.com/46667772/51159902-42406200-1840-11e9-95c1-bb1cd3189a73.png">
<img width="665" alt="screen shot 2019-01-14 at 9 02 27 pm" src="https://user-images.githubusercontent.com/46667772/51159903-42406200-1840-11e9-9c2b-4e7c00938698.png">

**Comment by rileydr** [comment] 2019-01-15 05:08
Also - Sorry for "dog piling" with a slightly different issue. :/

**Comment by FranticRain** [comment] 2019-01-15 13:09
@PWAG Glad you got it fixed.

@rileydr Yes. I understood exactly what your problem is. It's not uncommon. macOS just thinks that you aren't the one clicking on it because of something with your machine. I don't know what hardware or software is causing it, but it's a "feature."

**Comment by FranticRain** [comment] 2019-01-15 13:10
Closing this issue since OP has found a solution.

**Closed** 2019-01-15 13:10 UTC
